import { Layout } from '@/components/Layout';
import { AlertTriangle } from 'lucide-react';
import { usePageTitle } from '@/hooks/usePageTitle';

export default function Disclaimer() {
  usePageTitle('Disclaimer — Educational Use & Medical Notice');
  return (
    <Layout>
      <div className="py-16 md:py-24 bg-slate-50 min-h-screen">
        <div className="container mx-auto max-w-3xl px-4">
          
          <div className="bg-red-50 border-l-4 border-red-600 p-6 rounded-r-xl mb-12 shadow-sm">
            <div className="flex items-start">
              <AlertTriangle className="h-6 w-6 text-red-600 mr-4 shrink-0 mt-1" />
              <div>
                <h2 className="text-xl font-bold text-red-900 mb-2">Important Notice</h2>
                <p className="text-red-800 leading-relaxed">
                  This test is provided for educational, self-discovery, and entertainment purposes only. It is not a clinical diagnostic tool and cannot replace a formal psychological assessment.
                </p>
              </div>
            </div>
          </div>

          <h1 className="text-3xl font-bold text-slate-900 mb-6">Full Disclaimer</h1>
          
          <div className="prose prose-slate max-w-none">
            <h3>Not Clinical Advice</h3>
            <p>
              The intelligence assessments provided on FreeIQTest.online are designed to estimate general cognitive ability based on psychometric theories. However, they are not administered in a controlled clinical environment by a licensed psychologist. Therefore, the results hold no legal, medical, or psychiatric validity.
            </p>

            <h3>Accuracy and Validity</h3>
            <p>
              While we utilize rigorous statistical methods and continuously calibrate our question bank to align with standard IQ distributions (Mean = 100, SD = 15), online testing is subject to variables we cannot control, such as user distraction, fatigue, or prior exposure to similar puzzles. Your score here may differ from a professionally administered test like the WAIS-IV or Stanford-Binet.
            </p>

            <h3>Personal Use Only</h3>
            <p>
              Scores generated by this platform should not be used as the basis for significant life decisions, academic placements, employment screening, or psychological diagnosis. If you require an official IQ score for Mensa admission, academic accommodation, or clinical purposes, please consult a qualified healthcare professional.
            </p>

            <h3>Limitation of Liability</h3>
            <p>
              By using this site, you agree that FreeIQTest and its operators are not liable for any psychological distress, decisions made, or consequences arising from the interpretation of your test results.
            </p>
          </div>

        </div>
      </div>
    </Layout>
  );
}